FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . /app

CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8001"]