version: "3.8"
services:
  # Django App
  email_service:
    container_name: email_service
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && 
             gunicorn core.wsgi:application --bind 0.0.0.0:8002"
    ports:
      - 8002:8002
    depends_on:
      db_email:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - IN_DOCKER=true

  # Event Queue Kafka
  # queue_email:
  # build: .
  # command: >
  # sh -c "python consumer.py"
  # depends_on:
  # - db

  db_email:
    image: postgres
    container_name: django_email_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: solopython_email_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_email_METHOD: trust
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: django_email_api_redis
    ports:
      - 6381:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
